apply plugin: 'java-library'

if (findProperty("customUploadGradlePluginUrl") != null) {
    apply from: findProperty("customUploadGradlePluginUrl")
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    api "com.google.code.gson:gson:2.8.5"
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

//apply plugin: "com.vanniktech.maven.publish"